# Generated by Django 4.2 on 2023-08-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0006_headerparts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.FileField(upload_to='Uploads', verbose_name='Banner')),
                ('product_title', models.CharField(max_length=50, verbose_name='Ürün Başlığı')),
                ('product_description', models.TextField(max_length=150, verbose_name='Ürün Açıklaması')),
            ],
        ),
    ]
